# Generated by Django 4.2.11 on 2024-03-16 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_space_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main.Reservation.space+', to='facilities.space'),
        ),
    ]
