# Generated by Django 4.2.11 on 2024-03-13 11:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('max_capacity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('space_type', models.CharField(choices=[('Meeting Room', 'Meeting Room'), ('Open Seating', 'Open Seating')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.CharField(choices=[('09:00-11:00', '09:00-11:00'), ('11:00-13:00', '11:00-13:00'), ('13:00-15:00', '13:00-15:00'), ('15:00-17:00', '15:00-17:00'), ('17:00-19:00', '17:00-19:00')], max_length=20)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.space')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
